spring:
  profiles:
    include:
      - domain

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs
  paths-to-match: /api/**

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: development